function [rocketparamIDs, envparamIDs] = paramNames(simulatior3D)
%PARAMNAMES gives the names of the parameters that can be modified in the given simulator.
%   INPUT
%       simulatior3D          Simulator object
%   OUTPUTS
%       rocketparamIDs  Names of the rocket parameters
%       envparamIDs     Names of the environments parameters

if class(simulatior3D) == "multilayerwindSimulator3D" ... 
   || class(simulatior3D) == "multilayerwindSimulator3D_ode45" ... 
   || class(simulatior3D) == "multilayerwindSimulator3D_ode23" ...
   || class(simulatior3D) == "multilayerwindSimulator3D_ode113" ...
   || class(simulatior3D) == "multilayerwindSimulator3D_ode15s" ...
   || class(simulatior3D) == "multilayerwindSimulator3D_ode23s" ...
   || class(simulatior3D) == "multilayerwindSimulator3D_ode23t" ...
   || class(simulatior3D) == "multilayerwindSimulator3D_ode23tb"
        
    
    rocketparamIDs=["dmin" "dd" "z1" "z12" "z23" "numFins" "finRootPosition" "finSpan" "finRootChord" "finTipChord" "finSweepDistance" ...
                    "finThickness" "numLaunchLugs" "lugSurfaceArea" "emptyMass" "emptyInertia" "emptyCenterOfMass" "airbrakePosition" "numAirbrakes" "airbrakeAngle" ... 
                    "payloadMass" "mainParachuteDragArea" "drogueParachuteDragArea" "mainParachuteDeploymentAltitude" "interMotorDistance" "motor_diaP" ...
                    "motor_lengthP" "propel_massP" "motor_massP" "motor_diaF" "motor_lengthF" "propel_massF" ...
                    "motor_massF" "Burn_Time" "railTime" "flightTime"];
                
    envparamIDs   =["groundTemperature" "groundPressure" "groundHumidity"  ... 
                    "startAltitude" "dTdh" "railLength" "railAngle" "railAzimuth"...
                    "Vi1" "Vi2" "Vi3" "Vi4" "Vi5" "Vi6" "ai1" "ai2" "ai3" "ai4" "ai5" "ai6"];
else
    error("Error: the sensitivity analysis is not implemented for this simulator")
end

end

